# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
 - rvm use system
 - sudo gem install cocoapods -v '0.39.0'
 - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/EMEmojiableBtn.xcworkspace -scheme EMEmojiableBtn-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
